version: '3'

services:
  wg:
    build:
      context: .
      dockerfile: Dockerfile
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    ports:
      - 5000:5000
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /etc/wireguard/wg0.conf:/etc/wireguard/wg0.conf
